import type { RawCard, RawCharacter } from '../../types';

// Shared shape with engine's internal GameData, kept here for typed fetch.
export interface GameData {
  cards?: { result: Record<string, RawCard> };
  characters?: { result: Record<string, RawCharacter> };
}

/**
 * Load cards and characters JSON generated by the exporter.
 * Throws a descriptive error when network/parse fails, so callers can surface it.
 */
export async function fetchGameData(): Promise<GameData> {
  const [cardsRes, charactersRes] = await Promise.all([
    fetch('./cards.json'),
    fetch('./characters.json'),
  ]);

  if (!cardsRes.ok) throw new Error(`加载 cards.json 失败: ${cardsRes.status}`);
  if (!charactersRes.ok) throw new Error(`加载 characters.json 失败: ${charactersRes.status}`);

  const cards = (await cardsRes.json()) as any;
  const characters = (await charactersRes.json()) as any;
  // Basic shape guards
  const data: GameData = {
    cards: cards && typeof cards === 'object' ? (cards as GameData['cards']) : { result: {} },
    characters: characters && typeof characters === 'object' ? (characters as GameData['characters']) : { result: {} },
  };
  return data;
}

