/** this file is auto generated */
import * as TableContext from "./context";
import { IEnemies, EnemiesTID, toEnemiesTID, EnemiesRepo } from "./enemies";
        
const raw = {
  "tids": [
    "40060001",
    "40060002",
    "40060003",
    "40060004",
    "40060005",
    "40060006",
    "40060007"
  ],
  "result": {
    "40060001": {
      "_tid": "40060001",
      "sector": 40,
      "category": 6,
      "serial": 1,
      "name": "裂界餍爬者",
      "family": "SHAMBLER",
      "hp": 220,
      "damage": 24,
      "moveSpeed": 3.4,
      "radius": 12,
      "attackStyle": "AUTO",
      "attackInterval": 1.8,
      "projectileSpeed": 18,
      "projectileLifetime": 0.9,
      "projectileSprite": "fx/projectiles/spittle.png",
      "impactSprite": "fx/impact/slime.png",
      "weakness": "FIRE",
      "resistance": "VOID",
      "lootTable": "loot:ichor_minor",
      "sanityDamage": 6,
      "combatNotes": "投掷腐质胆汁，落地后留下灼蚀雾。",
      "xp": 18,
      "sprite": "ui/assets/topdown/top-down-shooter/characters/body/3.png",
      "spriteScale": 0.9,
      "deathSprite": "ui/assets/topdown/top-down-shooter/effects/explosion.png",
      "deathSfx": "ui/assets/topdown/top-down-shooter/sounds/explosion-2.wav",
      "attackSfx": "ui/assets/topdown/top-down-shooter/sounds/shoot-2.wav"
    },
    "40060002": {
      "_tid": "40060002",
      "sector": 40,
      "category": 6,
      "serial": 2,
      "name": "聆渊歌祭徒",
      "family": "CULTIST",
      "hp": 260,
      "damage": 32,
      "moveSpeed": 3.1,
      "radius": 14,
      "attackStyle": "BURST",
      "attackInterval": 2.4,
      "projectileSpeed": 22,
      "projectileLifetime": 0.85,
      "projectileSprite": "fx/projectiles/choir_note.png",
      "impactSprite": "fx/impact/chorus.png",
      "weakness": "LIGHT",
      "resistance": "VOID",
      "lootTable": "loot:choir_cache",
      "sanityDamage": 9,
      "combatNotes": "三连音符袭击，第三发附加畏惧层。",
      "xp": 26,
      "sprite": "ui/assets/topdown/top-down-shooter/characters/body/2.png",
      "spriteScale": 0.94,
      "deathSprite": "ui/assets/topdown/top-down-shooter/effects/4.png",
      "deathSfx": "ui/assets/topdown/top-down-shooter/sounds/death.wav",
      "attackSfx": "ui/assets/topdown/top-down-shooter/sounds/shoot-3.wav"
    },
    "40060003": {
      "_tid": "40060003",
      "sector": 40,
      "category": 6,
      "serial": 3,
      "name": "渊喉呼嚎者",
      "family": "ABERRATION",
      "hp": 340,
      "damage": 36,
      "moveSpeed": 3.6,
      "radius": 16,
      "attackStyle": "BURST",
      "attackInterval": 2.6,
      "projectileSpeed": 28,
      "projectileLifetime": 0.7,
      "projectileSprite": "fx/projectiles/howl_wave.png",
      "impactSprite": "fx/impact/howl.png",
      "weakness": "LIGHT",
      "resistance": "FROST",
      "lootTable": "loot:howler_pouch",
      "sanityDamage": 12,
      "combatNotes": "扇形震荡波附加 3 秒理智流失。",
      "xp": 32,
      "sprite": "ui/assets/topdown/top-down-shooter/characters/body/1.png",
      "spriteScale": 0.92,
      "deathSprite": "ui/assets/topdown/top-down-shooter/effects/3.png",
      "deathSfx": "ui/assets/topdown/top-down-shooter/sounds/explosion-3.wav",
      "attackSfx": "ui/assets/topdown/top-down-shooter/sounds/sword-2.wav"
    },
    "40060004": {
      "_tid": "40060004",
      "sector": 40,
      "category": 6,
      "serial": 4,
      "name": "虚壳哨兵",
      "family": "CONSTRUCT",
      "hp": 420,
      "damage": 42,
      "moveSpeed": 2.6,
      "radius": 18,
      "attackStyle": "BEAM",
      "attackInterval": 1.45,
      "projectileSpeed": 64,
      "projectileLifetime": 0.6,
      "projectileSprite": "fx/projectiles/null_beam.png",
      "impactSprite": "fx/impact/null_burn.png",
      "weakness": "VOID",
      "resistance": "KINETIC",
      "lootTable": "loot:sentinel_cache",
      "sanityDamage": 10,
      "combatNotes": "扫射光束前有 0.6 秒警示。",
      "xp": 38,
      "sprite": "ui/assets/topdown/top-down-shooter/characters/turret/2.png",
      "spriteScale": 1.05,
      "deathSprite": "ui/assets/topdown/top-down-shooter/effects/5.png",
      "deathSfx": "ui/assets/topdown/top-down-shooter/sounds/explosion-1.wav",
      "attackSfx": "ui/assets/topdown/top-down-shooter/sounds/alert.wav"
    },
    "40060005": {
      "_tid": "40060005",
      "sector": 40,
      "category": 6,
      "serial": 5,
      "name": "堕港掘锚者",
      "family": "CONSTRUCT",
      "hp": 520,
      "damage": 55,
      "moveSpeed": 2.2,
      "radius": 24,
      "attackStyle": "MANUAL",
      "attackInterval": 1.1,
      "projectileSpeed": 0,
      "projectileLifetime": 0,
      "projectileSprite": "fx/projectiles/dredger_slam.png",
      "impactSprite": "fx/impact/dredger_slam.png",
      "weakness": "FIRE",
      "resistance": "KINETIC",
      "lootTable": "loot:dredger_core",
      "sanityDamage": 14,
      "combatNotes": "冲撞灯塔并引发地震波，需快速躲避。",
      "xp": 46,
      "sprite": "ui/assets/topdown/top-down-shooter/characters/tank.png",
      "spriteScale": 0.85,
      "deathSprite": "ui/assets/topdown/top-down-shooter/effects/explosion.png",
      "deathSfx": "ui/assets/topdown/top-down-shooter/sounds/explosion-3.wav",
      "attackSfx": "ui/assets/topdown/top-down-shooter/sounds/flame-thrower.wav"
    },
    "40060006": {
      "_tid": "40060006",
      "sector": 40,
      "category": 6,
      "serial": 6,
      "name": "无数碎影",
      "family": "ABERRATION",
      "hp": 130,
      "damage": 14,
      "moveSpeed": 3.6,
      "radius": 10,
      "attackStyle": "BURST",
      "attackInterval": 2.4,
      "projectileSpeed": 18,
      "projectileLifetime": 0.9,
      "projectileSprite": "fx/projectiles/fragment_dart.png",
      "impactSprite": "fx/impact/fragment_spark.png",
      "weakness": "LIGHT",
      "resistance": "VOID",
      "lootTable": "loot:fragment_cache",
      "sanityDamage": 6,
      "combatNotes": "碎影快速游走射击，首波练习走位。",
      "xp": 16,
      "sprite": "ui/assets/topdown/top-down-shooter/characters/head/9.png",
      "spriteScale": 0.8,
      "deathSprite": "ui/assets/topdown/top-down-shooter/effects/2.png",
      "deathSfx": "ui/assets/topdown/top-down-shooter/sounds/shoot-destroy.wav",
      "attackSfx": "ui/assets/topdown/top-down-shooter/sounds/shoot-1.wav"
    },
    "40060007": {
      "_tid": "40060007",
      "sector": 40,
      "category": 6,
      "serial": 7,
      "name": "虚潮行者",
      "family": "SHAMBLER",
      "hp": 150,
      "damage": 12,
      "moveSpeed": 2.9,
      "radius": 16,
      "attackStyle": "MANUAL",
      "attackInterval": 0,
      "projectileSpeed": 0,
      "projectileLifetime": 0,
      "projectileSprite": "",
      "impactSprite": "",
      "weakness": "LIGHT",
      "resistance": "VOID",
      "lootTable": "loot:ichor_minor",
      "sanityDamage": 4,
      "combatNotes": "只会贴身缠斗的虚潮行者，用来熟悉位移。",
      "xp": 14,
      "sprite": "ui/assets/topdown/top-down-shooter/characters/head/5.png",
      "spriteScale": 0.88,
      "deathSprite": "ui/assets/topdown/top-down-shooter/effects/explosion.png",
      "deathSfx": "ui/assets/topdown/top-down-shooter/sounds/death.wav",
      "attackSfx": ""
    }
  },
  "collisions": []
}

export const enemiesRaw = raw;
export const enemiesTids: EnemiesTID[] = raw.tids.map(toEnemiesTID);
export const enemiesRecords: Record<EnemiesTID, IEnemies> = Object.fromEntries(
  Object.entries(raw.result).map(([tid, value]) => [toEnemiesTID(tid), value as IEnemies])
);
export const enemies = enemiesRecords;
export const enemiesRepo = EnemiesRepo.fromRaw(raw);
