/** this file is auto generated */
import * as TableContext from "./context";
import { IWeapons, WeaponsTID, toWeaponsTID, WeaponsRepo } from "./weapons";
        
const raw = {
  "tids": [
    "20020001",
    "20020002",
    "20020003",
    "20020004",
    "20020005",
    "20020006"
  ],
  "result": {
    "20020001": {
      "_tid": "20020001",
      "sector": 20,
      "category": 2,
      "serial": 1,
      "name": "霓虹符文左轮",
      "categoryName": "霓虹侧臂",
      "attackStyle": "MANUAL",
      "damage": 62,
      "damageType": "KINETIC",
      "fireRate": 0.38,
      "reload": 1.6,
      "magazine": 6,
      "spread": 2.4,
      "projectileSpeed": 48,
      "maxRange": 30,
      "projectileLifetime": 0.62,
      "travelSprite": "fx/projectiles/revolver.png",
      "impactSprite": "fx/impact/sparks.png",
      "muzzleSprite": "fx/muzzle/flame.png",
      "notes": "轻量侧臂，暴击可震慑敌人 0.3 秒。",
      "fireSfx": "ui/assets/sfx/weapons/runic_revolver_fire.wav",
      "impactSfx": "ui/assets/sfx/weapons/runic_revolver_hit.wav",
      "projectileScale": 0.68,
      "impactScale": 0.9
    },
    "20020002": {
      "_tid": "20020002",
      "sector": 20,
      "category": 2,
      "serial": 2,
      "name": "共鸣光谱射线",
      "categoryName": "以太光束",
      "attackStyle": "BEAM",
      "damage": 18,
      "damageType": "VOID",
      "fireRate": 0.12,
      "reload": 2.4,
      "magazine": 0,
      "spread": 0,
      "projectileSpeed": 78,
      "maxRange": 24,
      "projectileLifetime": 0.3,
      "travelSprite": "fx/projectiles/beam_ray.png",
      "impactSprite": "fx/impact/void_burst.png",
      "muzzleSprite": "fx/muzzle/chorus.png",
      "notes": "持续瞄准时，伤害每秒提升 +4。",
      "fireSfx": "ui/assets/sfx/weapons/chorus_ray_fire.wav",
      "impactSfx": "ui/assets/sfx/weapons/chorus_ray_hit.wav",
      "projectileScale": 0.85,
      "impactScale": 1.05
    },
    "20020003": {
      "_tid": "20020003",
      "sector": 20,
      "category": 2,
      "serial": 3,
      "name": "潮裂破晓炮",
      "categoryName": "潮汐重炮",
      "attackStyle": "BURST",
      "damage": 96,
      "damageType": "FROST",
      "fireRate": 0.22,
      "reload": 2.8,
      "magazine": 2,
      "spread": 4.5,
      "projectileSpeed": 36,
      "maxRange": 20,
      "projectileLifetime": 0.55,
      "travelSprite": "fx/projectiles/tide_shell.png",
      "impactSprite": "fx/impact/frost_shatter.png",
      "muzzleSprite": "fx/muzzle/water.png",
      "notes": "0.35 秒后裂解成三枚霜晶碎片。",
      "fireSfx": "ui/assets/sfx/weapons/tidebreaker_launcher_fire.wav",
      "impactSfx": "ui/assets/sfx/weapons/tidebreaker_launcher_hit.wav",
      "projectileScale": 0.75,
      "impactScale": 1.15
    },
    "20020004": {
      "_tid": "20020004",
      "sector": 20,
      "category": 2,
      "serial": 4,
      "name": "脉冲疾能卡宾枪",
      "categoryName": "脉冲步枪",
      "attackStyle": "MANUAL",
      "damage": 44,
      "damageType": "LIGHT",
      "fireRate": 0.26,
      "reload": 1.9,
      "magazine": 18,
      "spread": 3.1,
      "projectileSpeed": 64,
      "maxRange": 32,
      "projectileLifetime": 0.5,
      "travelSprite": "fx/projectiles/pulse.png",
      "impactSprite": "fx/impact/pulse_flash.png",
      "muzzleSprite": "fx/muzzle/pulse_muzzle.png",
      "notes": "跟随节奏射击可叠加动量，加速装填。",
      "fireSfx": "ui/assets/sfx/weapons/pulse_carbine_fire.wav",
      "impactSfx": "ui/assets/sfx/weapons/pulse_carbine_hit.wav",
      "projectileScale": 0.7,
      "impactScale": 1
    },
    "20020005": {
      "_tid": "20020005",
      "sector": 20,
      "category": 2,
      "serial": 5,
      "name": "幽幕散裂霰炮",
      "categoryName": "暗影霰弹",
      "attackStyle": "BURST",
      "damage": 28,
      "damageType": "VOID",
      "fireRate": 0.45,
      "reload": 2.1,
      "magazine": 4,
      "spread": 8,
      "projectileSpeed": 28,
      "maxRange": 18,
      "projectileLifetime": 0.4,
      "travelSprite": "fx/projectiles/umbral_pellet.png",
      "impactSprite": "fx/impact/void_scar.png",
      "muzzleSprite": "fx/muzzle/umbral.png",
      "notes": "近距离命中同一目标时，每颗弹丸额外 +6 伤害。",
      "fireSfx": "ui/assets/sfx/weapons/umbral_scattergun_fire.wav",
      "impactSfx": "ui/assets/sfx/weapons/umbral_scattergun_hit.wav",
      "projectileScale": 0.78,
      "impactScale": 1.1
    },
    "20020006": {
      "_tid": "20020006",
      "sector": 20,
      "category": 2,
      "serial": 6,
      "name": "蚀光穿梭矛阵",
      "categoryName": "熔蚀矛阵",
      "attackStyle": "AUTO",
      "damage": 54,
      "damageType": "FIRE",
      "fireRate": 0.32,
      "reload": 2.2,
      "magazine": 5,
      "spread": 2.2,
      "projectileSpeed": 52,
      "maxRange": 32,
      "projectileLifetime": 0.7,
      "travelSprite": "fx/projectiles/eclipse_javelin.png",
      "impactSprite": "fx/impact/eclipse_burst.png",
      "muzzleSprite": "fx/muzzle/eclipse.png",
      "notes": "自导矛头炸裂出炽焰柱，擅长清理聚群敌人。",
      "fireSfx": "ui/assets/sfx/weapons/eclipse_javelin_fire.wav",
      "impactSfx": "ui/assets/sfx/weapons/eclipse_javelin_hit.wav",
      "projectileScale": 0.82,
      "impactScale": 1.25
    }
  },
  "collisions": []
}

export const weaponsRaw = raw;
export const weaponsTids: WeaponsTID[] = raw.tids.map(toWeaponsTID);
export const weaponsRecords: Record<WeaponsTID, IWeapons> = Object.fromEntries(
  Object.entries(raw.result).map(([tid, value]) => [toWeaponsTID(tid), value as IWeapons])
);
export const weapons = weaponsRecords;
export const weaponsRepo = WeaponsRepo.fromRaw(raw);
